import { cp, mkdir, readdir, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));

export async function installSkills({
  targetDir,
  categories = null,
  harnessName = "opencode",
}) {
  const sourceSkillsDir = join(__dirname, "..", "skills");

  if (!existsSync(sourceSkillsDir)) {
    throw new Error(`Source skills directory not found: ${sourceSkillsDir}`);
  }

  const allEntries = await readdir(sourceSkillsDir, { withFileTypes: true });
  const availableCategories = allEntries.filter((e) => e.isDirectory()).map((e) => e.name);

  const selectedCategories = categories
    ? categories.filter((c) => availableCategories.includes(c))
    : availableCategories;

  if (selectedCategories.length === 0) {
    throw new Error(
      `No matching skill categories found. Available: ${availableCategories.join(", ")}`
    );
  }

  await mkdir(targetDir, { recursive: true });

  let copied = 0;
  const installed = [];

  for (const cat of selectedCategories) {
    const sourceCat = join(sourceSkillsDir, cat);
    const targetCat = join(targetDir, cat);

    await mkdir(targetCat, { recursive: true });

    const files = await readdir(sourceCat);
    const mdFiles = files.filter((f) => f.endsWith(".md"));

    for (const file of mdFiles) {
      await cp(join(sourceCat, file), join(targetCat, file));
      installed.push(`${cat}/${file}`);
      copied++;
    }
  }

  return { copied, installed, targetDir, harnessName };
}

export async function initProjectMemory({ targetDir }) {
  const docsDir = join(targetDir, "docs");
  const projectAiDir = join(targetDir, ".project-ai");

  await mkdir(docsDir, { recursive: true });
  await mkdir(projectAiDir, { recursive: true });

  const docsFiles = [
    {
      name: "index.md",
      content: [
        "# Project Index",
        "",
        "> Auto-generated by @asaje/skills. Fill with your project details.",
        "",
        "## Stack",
        "",
        "## Architecture",
        "",
        "## Key Libraries",
        "",
        "## Essential Conventions",
        "",
      ].join("\n"),
    },
    {
      name: "conventions.md",
      content: [
        "# Project Conventions",
        "",
        "> Auto-generated by @asaje/skills. Document your coding conventions here.",
        "",
      ].join("\n"),
    },
    {
      name: "architecture.md",
      content: [
        "# Architecture",
        "",
        "> Auto-generated by @asaje/skills. Document your architecture here.",
        "",
      ].join("\n"),
    },
    {
      name: "decisions.md",
      content: [
        "# Architecture Decisions",
        "",
        "> Auto-generated by @asaje/skills.",
        "> Record key decisions with date, context, options, rationale, and consequences.",
        "",
      ].join("\n"),
    },
    {
      name: "glossary.md",
      content: [
        "# Glossary",
        "",
        "> Auto-generated by @asaje/skills. Define domain-specific terminology here.",
        "",
      ].join("\n"),
    },
  ];

  for (const { name, content } of docsFiles) {
    const filepath = join(docsDir, name);
    if (!existsSync(filepath)) {
      await writeFile(filepath, content, "utf-8");
    }
  }

  const projectJsonPath = join(projectAiDir, "project.json");
  if (!existsSync(projectJsonPath)) {
    await writeFile(
      projectJsonPath,
      JSON.stringify(
        {
          name: "",
          description: "",
          stack: { frontend: "", backend: "", database: "", orm: "" },
          packageManager: "",
          architecture: "",
          tools: { quality: "", testing: "", ci: "" },
          conventions: [],
          generatedBy: "@asaje/skills",
        },
        null,
        2
      ),
      "utf-8"
    );
  }

  const inventoryPath = join(projectAiDir, "inventory.json");
  if (!existsSync(inventoryPath)) {
    await writeFile(
      inventoryPath,
      JSON.stringify(
        {
          components: [],
          hooks: [],
          services: [],
          helpers: [],
          routes: [],
          generatedBy: "@asaje/skills",
        },
        null,
        2
      ),
      "utf-8"
    );
  }

  const lockPath = join(projectAiDir, "skills.lock.json");
  if (!existsSync(lockPath)) {
    await writeFile(
      lockPath,
      JSON.stringify(
        {
          skills: [],
          installedAt: new Date().toISOString(),
          generatedBy: "@asaje/skills",
        },
        null,
        2
      ),
      "utf-8"
    );
  }

  return { docsDir, projectAiDir };
}
